name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test configuration
      run: |
        python -c "from src.mfl_monitor.utils.config import Config; print('Config loaded successfully')"
    
    - name: Test imports
      run: |
        python -c "from src.mfl_monitor.core.analyzer import TransactionAnalyzer; print('Analyzer imported successfully')"
        python -c "from src.mfl_monitor.apis.mfl_api import MFLAPI; print('MFL API imported successfully')"
        python -c "from src.mfl_monitor.apis.discord_bot import DiscordNotifier; print('Discord bot imported successfully')"
